module.exports = {
  apps: [
    {
      name: "j12-api-hml",
      cwd: __dirname,
      // HML deve executar exatamente a mesma composição de API da produção.
      script: "backend/server.js",
      interpreter: "node",
      // HML nunca compartilha o arquivo de secrets da producao.
      node_args: "--env-file=.env.hml",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      merge_logs: true,
      time: true,
      out_file: "logs/j12-api-hml.out.log",
      error_file: "logs/j12-api-hml.error.log",
      env: {
        NODE_ENV: "production",
        J12_ENVIRONMENT: "hml",
        HML_ISOLATED: "true",
        HML_REAL_INTEGRATIONS_ENABLED: "false",
        EMAIL_PROVIDER: "disabled",
        INTER_INTEGRATION_MODE: "disabled",
        HOST: "127.0.0.1",
        PORT: "3001",
        CORS_ORIGIN: "https://hml.app.j12sports.com.br,https://www.hml.app.j12sports.com.br",
      },
    },
    {
      name: "j12-frontend-hml",
      cwd: __dirname,
      script: "scripts/serve-ssr.mjs",
      interpreter: "node",
      args: "--host 127.0.0.1 --port 4173 --api-target http://127.0.0.1:3001 --ssr-timeout-ms 30000",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "logs/j12-frontend-hml.out.log",
      error_file: "logs/j12-frontend-hml.error.log",
      env: {
        NODE_ENV: "production",
        J12_ENVIRONMENT: "hml",
        HML_ISOLATED: "true",
        API_TARGET: "http://127.0.0.1:3001",
        SSR_API_URL: "http://127.0.0.1:3001",
        API_BASE_URL: "http://127.0.0.1:3001",
        VITE_API_URL: "/__api",
      },
    },
  ],
};
