module.exports = {
  apps: [
    {
      name: "j12-api",
      cwd: __dirname,
      script: "server/index.mjs",
      interpreter: "node",
      node_args: "--env-file=.env.api.production",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      merge_logs: true,
      time: true,
      out_file: "logs/j12-api.out.log",
      error_file: "logs/j12-api.error.log",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "j12-frontend",
      cwd: __dirname,
      script: "scripts/serve-ssr.mjs",
      interpreter: "node",
      args: "--host 127.0.0.1 --port 4173 --api-target http://127.0.0.1:3001 --ssr-timeout-ms 30000",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "logs/j12-frontend.out.log",
      error_file: "logs/j12-frontend.error.log",
      env: {
        NODE_ENV: "production",
        API_TARGET: "http://127.0.0.1:3001",
      },
    },
  ],
};
