const JOURNEYS = Object.freeze([
  journey(1, "Admin autentica", "admin", "/login", [], "Sessao admin valida e redirecionamento"),
  journey(
    2,
    "Admin cria/consulta aluno",
    "admin",
    "/alunos",
    [1],
    "Aluno sintetico persistido e visivel",
  ),
  journey(
    3,
    "Responsavel e vinculado",
    "admin",
    "/alunos",
    [2],
    "Vinculo persistido sem acesso cruzado",
  ),
  journey(4, "Matricula e criada", "admin", "/admin/enrollments", [2, 3], "Matricula persistida"),
  journey(5, "Aluno entra em turma", "admin", "/turmas", [4], "Vinculo de turma persistido"),
  journey(
    6,
    "Obrigacao financeira e gerada",
    "admin",
    "/admin/financeiro",
    [4],
    "Obrigacao unica persistida",
  ),
  journey(
    7,
    "Cobranca e criada ou simulada com seguranca",
    "admin",
    "/admin/financeiro",
    [6],
    "Cobranca local idempotente",
  ),
  journey(
    8,
    "Pagamento e processado ou simulado",
    "admin",
    "/admin/financeiro",
    [7],
    "Simulacao local sem provedor externo",
  ),
  journey(
    9,
    "Conciliacao atualiza status",
    "admin",
    "/admin/financeiro",
    [8],
    "Status local coerente sem baixa indevida",
  ),
  journey(
    10,
    "Automacao e executada",
    "admin",
    "/admin/financeiro",
    [7],
    "Execucao local auditada sem n8n",
  ),
  journey(
    11,
    "Historico e persistido",
    "admin",
    "/admin/financeiro/automacoes/historico",
    [10],
    "Historico persistido",
  ),
  journey(
    12,
    "Admin consulta historico",
    "admin",
    "/admin/financeiro/automacoes/historico",
    [11],
    "Historico renderizado",
  ),
  journey(
    13,
    "BI reflete dados",
    "admin",
    "/admin/bi",
    [2, 6, 9],
    "Indicadores refletem dados sinteticos",
  ),
  journey(
    14,
    "Professor consulta turma",
    "professor",
    "/professor/presencas",
    [5],
    "Somente turmas atribuidas",
  ),
  journey(
    15,
    "Professor registra presenca",
    "professor",
    "/professor/presencas",
    [14],
    "Presenca persistida e atualizada",
  ),
  journey(
    16,
    "Aluno consulta seus dados",
    "aluno",
    "/portal-aluno/dashboard",
    [2, 4],
    "Somente dados da sessao",
  ),
  journey(
    17,
    "Responsavel consulta dependente",
    "responsavel",
    "/portal-responsavel/dashboard",
    [3],
    "Somente dependentes vinculados",
  ),
  journey(
    18,
    "Reserva de quadra e criada",
    "admin",
    "/admin/quadras",
    [1],
    "Reserva sintetica persistida",
  ),
  journey(
    19,
    "Conflito de horario e impedido",
    "admin",
    "/admin/quadras",
    [18],
    "Segunda reserva conflitante rejeitada",
  ),
  journey(
    20,
    "Campeonato e criado",
    "admin",
    "/admin/campeonatos",
    [1],
    "Campeonato sintetico persistido",
  ),
  journey(
    21,
    "Portal publico exibe campeonato",
    "public",
    "/campeonatos",
    [20],
    "Campeonato publicado renderizado sem PII",
  ),
]);

function journey(id, name, role, route, dependencies, expected) {
  return Object.freeze({
    id: `J${String(id).padStart(2, "0")}`,
    name,
    role,
    route,
    dependencies: Object.freeze(dependencies.map((item) => `J${String(item).padStart(2, "0")}`)),
    data: "[E2E-SYNTHETIC] / example.test / sem contato roteavel",
    expected,
  });
}

module.exports = { JOURNEYS };
