CREATE TABLE IF NOT EXISTS alunos (
  id VARCHAR(64) PRIMARY KEY,
  nome VARCHAR(191) NOT NULL,
  email VARCHAR(191) NULL,
  telefone VARCHAR(50) NULL,
  data_nascimento DATE NULL,
  responsavel VARCHAR(191) NULL,
  telefone_responsavel VARCHAR(50) NULL,
  modalidade VARCHAR(191) NULL,
  turma VARCHAR(191) NULL,
  plano VARCHAR(191) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'ativo',
  matricula_em DATE NULL,
  numero_matricula VARCHAR(50) NULL,
  cpf VARCHAR(20) NULL,
  rg VARCHAR(30) NULL,
  sexo VARCHAR(30) NULL,
  origem_cadastro VARCHAR(100) NULL,
  matricula_publica_protocolo VARCHAR(100) NULL,
  unidades_json LONGTEXT NULL,
  turmas_json LONGTEXT NULL,
  planos_json LONGTEXT NULL,
  horarios_json LONGTEXT NULL,
  matricula_json LONGTEXT NULL,
  financeiro_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS financeiro (
  id VARCHAR(64) PRIMARY KEY,
  aluno_id VARCHAR(64) NOT NULL,
  aluno_nome VARCHAR(191) NOT NULL,
  descricao TEXT NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  valor DECIMAL(12,2) NOT NULL,
  vencimento DATE NOT NULL,
  pago_em DATE NULL,
  forma_pagamento VARCHAR(50) NULL,
  observacao TEXT NULL,
  responsavel_financeiro VARCHAR(191) NULL,
  responsavel_cpf VARCHAR(20) NULL,
  telefone_whatsapp VARCHAR(50) NULL,
  email VARCHAR(191) NULL,
  unidade VARCHAR(191) NULL,
  modalidade VARCHAR(191) NULL,
  turma VARCHAR(191) NULL,
  plano_id VARCHAR(64) NULL,
  plano_nome VARCHAR(191) NULL,
  periodicidade VARCHAR(30) NULL,
  competencia VARCHAR(32) NULL,
  valor_original DECIMAL(12,2) NULL,
  desconto_valor DECIMAL(12,2) NULL,
  desconto_percentual DECIMAL(10,2) NULL,
  bolsa_valor DECIMAL(12,2) NULL,
  bolsa_percentual DECIMAL(10,2) NULL,
  multa_percentual DECIMAL(10,2) NULL,
  juros_dia_percentual DECIMAL(10,2) NULL,
  valor_final DECIMAL(12,2) NULL,
  data_geracao DATE NULL,
  data_pagamento DATE NULL,
  status VARCHAR(30) NULL,
  tipo_cobranca VARCHAR(30) NULL,
  origem VARCHAR(30) NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  alterado_em DATETIME NULL,
  alterado_por VARCHAR(191) NULL,
  cancelamento_motivo TEXT NULL,
  desconto_motivo TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_financeiro_aluno (aluno_id),
  INDEX idx_financeiro_competencia (competencia),
  INDEX idx_financeiro_status (status)
);
