const assert = require("node:assert/strict");
const { test } = require("node:test");
const { Lead, LeadStage, LeadStatus } = require("../domain/lead.js");
const { CrmLeadService } = require("../application/crm-lead.service.js");
const { MySqlCrmLeadRepository } = require("../infrastructure/mysql-crm-lead.repository.js");
const migration = require("../../../database/migrations/20260717150000_create_crm_foundation_tables.js");
function input(overrides={}) { return { unitId:"u1",source:"Site",contactName:"<Maria>",contactEmail:" Test@Example.com ",contactPhone:"(11) 99999-9999",createdBy:"admin",...overrides }; }
test("Lead creates sanitized open lifecycle and immutable unit",()=>{ const lead=new Lead(input()); assert.equal(lead.status,LeadStatus.OPEN); assert.equal(lead.stage,LeadStage.NEW); assert.equal(lead.contactName,"Maria"); assert.equal(lead.contactEmail,"test@example.com"); assert.equal(lead.contactPhone,"11999999999"); assert.ok(Object.isFrozen(lead)); assert.throws(()=>new Lead(input({source:""})),/source/); });
test("Lead validates transitions and terminal idempotency",()=>{ const lead=new Lead(input()); const qualified=lead.changeStage(LeadStage.QUALIFIED,"admin","2026-07-17T10:00:00Z"); assert.equal(qualified.qualifiedAt,"2026-07-17T10:00:00Z"); const converted=qualified.convert("admin"); assert.equal(converted.convert("admin"),converted); assert.throws(()=>converted.changeStage(LeadStage.NEW,"admin"),(e)=>e.code==="CRM_LEAD_TERMINAL"); const lost=lead.lose("Sem interesse","admin"); assert.equal(lost.lose("outra","admin"),lost); });
test("application enforces unit authorization, consultative duplicate and no side effects",async()=>{ const calls=[]; const service=new CrmLeadService({authorizeUnit:(_c,u)=>u==="u1",repository:{async findByContactIdentity(){return null},async create(lead){calls.push("create");return lead}}}); const result=await service.create(input(),{userId:"admin"}); assert.equal(result.created,true); assert.deepEqual(calls,["create"]); await assert.rejects(()=>service.create(input({unitId:"u2"}),{userId:"admin"}),(e)=>e.code==="CRM_ACCESS_DENIED"); });
test("repository transition is transactional, scoped and history contains no contact PII",async()=>{ const calls=[]; const current=new Lead(input({id:"l1"})); const next=current.convert("admin","2026-07-17T11:00:00Z"); const repo=new MySqlCrmLeadRepository({queryRunner:async()=>[],transactionRunner:async(fn)=>fn({query:async(sql,params)=>{calls.push({sql,params});return sql.startsWith("SELECT")?[[{...next}]]:[];}})}); await repo.saveTransition({current,next,action:"CONVERTED",actorId:"admin"}); assert.equal(calls.length,3); assert.match(calls[0].sql,/WHERE id=\? AND unit_id=\?/); assert.doesNotMatch(JSON.stringify(calls[1].params),/example\.com|11999999999|Maria/); for(const call of calls) assert.doesNotMatch(call.sql,/\$\{|\+\s*(?:id|unit)/); });
test("migration creates two InnoDB tables, indexes, FKs and guarded down contract",()=>{ assert.match(migration.LEADS_SQL,/CREATE TABLE IF NOT EXISTS crm_leads/); assert.match(migration.HISTORY_SQL,/crm_lead_stage_history/); assert.match(migration.LEADS_SQL,/idx_crm_leads_unit_status/); assert.match(migration.HISTORY_SQL,/FOREIGN KEY \(lead_id\)/); assert.deepEqual(migration.TABLES,["crm_lead_stage_history","crm_leads"]); });
