const assert = require("node:assert/strict");
const { test } = require("node:test");
const { Lead, LeadStage, LeadStatus } = require("../domain/lead.js");
const { CrmLeadService } = require("../application/crm-lead.service.js");
const { MySqlCrmLeadRepository } = require("../infrastructure/mysql-crm-lead.repository.js");
function lead(stage=LeadStage.NEW,status=LeadStatus.OPEN){return new Lead({id:"l1",unitId:"u1",source:"Site",contactName:"Maria",createdBy:"admin",stage,status});}
test("canonical pipeline advances sequentially through WON",()=>{ let current=lead(); for(const stage of [LeadStage.CONTACTED,LeadStage.QUALIFIED,LeadStage.PROPOSAL,LeadStage.NEGOTIATION,LeadStage.WON]) current=current.moveTo(stage,{actor:"admin"}); assert.equal(current.stage,LeadStage.WON); assert.equal(current.status,LeadStatus.CONVERTED); assert.equal(current.isTerminal(),true); });
test("pipeline permits LOST from open stages and requires reason",()=>{ for(const stage of [LeadStage.NEW,LeadStage.CONTACTED,LeadStage.QUALIFIED,LeadStage.PROPOSAL,LeadStage.NEGOTIATION]){const current=lead(stage); assert.throws(()=>current.moveTo(LeadStage.LOST,{actor:"admin"}),(e)=>e.code==="CRM_LOST_REASON_REQUIRED"); const lost=current.moveTo(LeadStage.LOST,{actor:"admin",reason:"Sem interesse"}); assert.equal(lost.status,LeadStatus.LOST);} });
test("pipeline blocks skips, same stage, unknown stage and terminal movement before persistence",()=>{const current=lead(); assert.throws(()=>current.moveTo(LeadStage.QUALIFIED,{actor:"admin"}),(e)=>e.code==="CRM_STAGE_TRANSITION_INVALID"); assert.throws(()=>current.moveTo(LeadStage.NEW,{actor:"admin"}),(e)=>e.code==="CRM_STAGE_UNCHANGED"); assert.throws(()=>current.moveTo("UNKNOWN",{actor:"admin"}),(e)=>e.code==="CRM_STAGE_INVALID"); assert.throws(()=>lead(LeadStage.WON,LeadStatus.CONVERTED).moveTo(LeadStage.LOST,{actor:"admin",reason:"x"}));});
test("application validates missing and nonexistent lead",async()=>{const service=new CrmLeadService({authorizeUnit:()=>true,repository:{async findById(){return null}}}); await assert.rejects(()=>service.moveLeadToStage({}, {userId:"a",unitId:"u1"}),(e)=>e.code==="CRM_INPUT_INVALID"); await assert.rejects(()=>service.moveLeadToStage({leadId:"missing",nextStage:"CONTACTED"},{userId:"a",unitId:"u1"}),(e)=>e.code==="CRM_LEAD_NOT_FOUND");});
test("repository locks, compare-and-sets, appends history atomically and lists chronologically",async()=>{const calls=[];const current={...lead()};const next=lead().moveTo(LeadStage.CONTACTED,{actor:"admin"});const repo=new MySqlCrmLeadRepository({queryRunner:async(sql,p)=>{calls.push({sql,p});return[]},transactionRunner:async(fn)=>fn({query:async(sql,p)=>{calls.push({sql,p});if(sql.includes("FOR UPDATE"))return[[current]];if(sql.startsWith("UPDATE"))return{affectedRows:1};if(sql.startsWith("SELECT"))return[[{...next}]];return[];}})});const saved=await repo.saveStageTransition({leadId:"l1",unitId:"u1",next,action:"STAGE_CHANGED",actorId:"admin"});assert.equal(saved.stage,LeadStage.CONTACTED);assert.match(calls[0].sql,/FOR UPDATE/);assert.match(calls[1].sql,/stage=\? AND status=\?/);assert.match(calls[2].sql,/INSERT INTO crm_lead_stage_history/);await repo.listStageHistory({leadId:"l1",unitId:"u1"});assert.match(calls.at(-1).sql,/ORDER BY created_at ASC,id ASC/);});
test("concurrent stale update fails and prevents history",async()=>{const calls=[];const repo=new MySqlCrmLeadRepository({queryRunner:async()=>[],transactionRunner:async(fn)=>fn({query:async(sql)=>{calls.push(sql);if(sql.includes("FOR UPDATE"))return[[{...lead()}]];if(sql.startsWith("UPDATE"))return{affectedRows:0};return[];}})});await assert.rejects(()=>repo.saveStageTransition({leadId:"l1",unitId:"u1",next:lead().moveTo(LeadStage.CONTACTED,{actor:"a"}),action:"STAGE_CHANGED",actorId:"a"}),(e)=>e.code==="CRM_STAGE_CONFLICT");assert.equal(calls.some((sql)=>sql.startsWith("INSERT")),false);});
