#!/usr/bin/env node
let database;
function db() { return database || (database = require("../../config/db.js")); }
const TABLES = ["crm_lead_stage_history", "crm_leads"];
const LEADS_SQL = `CREATE TABLE IF NOT EXISTS crm_leads (id VARCHAR(64) PRIMARY KEY,unit_id VARCHAR(64) NOT NULL,person_id VARCHAR(64) NULL,source VARCHAR(64) NOT NULL,stage VARCHAR(32) NOT NULL,status VARCHAR(32) NOT NULL,assigned_to VARCHAR(64) NULL,contact_name VARCHAR(191) NOT NULL,contact_email VARCHAR(191) NULL,contact_phone VARCHAR(20) NULL,qualified_at DATETIME NULL,converted_at DATETIME NULL,lost_at DATETIME NULL,lost_reason VARCHAR(191) NULL,created_by VARCHAR(191) NOT NULL,updated_by VARCHAR(191) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,deleted_at DATETIME NULL,INDEX idx_crm_leads_unit_status (unit_id,status),INDEX idx_crm_leads_unit_stage (unit_id,stage),INDEX idx_crm_leads_source (source),INDEX idx_crm_leads_assigned (assigned_to),INDEX idx_crm_leads_created (created_at),INDEX idx_crm_leads_converted (converted_at),INDEX idx_crm_leads_lost (lost_at),INDEX idx_crm_leads_contact (unit_id,contact_email,contact_phone),CONSTRAINT fk_crm_leads_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`;
const HISTORY_SQL = `CREATE TABLE IF NOT EXISTS crm_lead_stage_history (id VARCHAR(64) PRIMARY KEY,lead_id VARCHAR(64) NOT NULL,unit_id VARCHAR(64) NOT NULL,previous_stage VARCHAR(32) NULL,new_stage VARCHAR(32) NOT NULL,previous_status VARCHAR(32) NULL,new_status VARCHAR(32) NOT NULL,action VARCHAR(32) NOT NULL,actor_id VARCHAR(191) NOT NULL,reason VARCHAR(191) NULL,created_at DATETIME NOT NULL,INDEX idx_crm_history_lead_created (lead_id,created_at),INDEX idx_crm_history_unit_created (unit_id,created_at),CONSTRAINT fk_crm_history_lead FOREIGN KEY (lead_id) REFERENCES crm_leads(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`;
async function up() { await db().query(LEADS_SQL); await db().query(HISTORY_SQL); return status(); }
async function status() { const states = await Promise.all(TABLES.map((name) => db().tableExists(name))); return { leads: states[1], history: states[0] }; }
async function down() { for (const name of TABLES) { if (!(await db().tableExists(name))) continue; const rows=await db().query(`SELECT COUNT(*) total FROM ${name}`); if(Number(rows[0]?.total||0)>0) throw new Error(`Refusing to drop non-empty ${name}.`); await db().query(`DROP TABLE ${name}`); } }
if(require.main===module){ const command=process.argv[2]||"status"; Promise.resolve({up,down,status}[command]?.()).then(console.log).catch((e)=>{console.error(e);process.exitCode=1;}); }
module.exports={ HISTORY_SQL, LEADS_SQL, TABLES, down, status, up };
