"use strict";

const EXIT_CODES = Object.freeze({
  CLEAN: 0,
  FINDINGS: 1,
  CRITICAL: 2,
  USAGE: 3,
  CONNECTION: 4,
  INTERNAL: 5,
});
const SEVERITIES = Object.freeze({
  INFO: "INFO",
  WARNING: "WARNING",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});
const LEDGER_STATES = Object.freeze({
  APPLIED: "LEDGER_APPLIED",
  PENDING: "LEDGER_PENDING",
  UNKNOWN: "UNKNOWN",
});
const PHYSICAL_STATES = Object.freeze({
  PRESENT: "PHYSICALLY_PRESENT",
  PARTIAL: "PARTIALLY_PRESENT",
  ABSENT: "PHYSICALLY_ABSENT",
  INCOMPATIBLE: "DRIFT_DETECTED",
  TABLE_OPTION_DRIFT: "TABLE_OPTION_DRIFT",
  NOT_ASSESSED: "UNKNOWN",
});

module.exports = { EXIT_CODES, SEVERITIES, LEDGER_STATES, PHYSICAL_STATES };
