/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as ProfessoresRouteImport } from './routes/professores'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as PresencaRouteImport } from './routes/presenca'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MeuPlanoRouteImport } from './routes/meu-plano'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AulaExperimentalRouteImport } from './routes/aula-experimental'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'

const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessoresRoute = ProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencaRoute = PresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPlanoRoute = MeuPlanoRouteImport.update({
  id: '/meu-plano',
  path: '/meu-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaExperimentalRoute = AulaExperimentalRouteImport.update({
  id: '/aula-experimental',
  path: '/aula-experimental',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/aula-experimental': typeof AulaExperimentalRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/planos': typeof PlanosRoute
  '/presenca': typeof PresencaRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/professores': typeof ProfessoresRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/turmas': typeof TurmasRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/aula-experimental': typeof AulaExperimentalRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/planos': typeof PlanosRoute
  '/presenca': typeof PresencaRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/professores': typeof ProfessoresRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/turmas': typeof TurmasRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/aula-experimental': typeof AulaExperimentalRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/financeiro': typeof FinanceiroRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/planos': typeof PlanosRoute
  '/presenca': typeof PresencaRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/professores': typeof ProfessoresRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/turmas': typeof TurmasRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/aula-experimental'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/forgot-password'
    | '/login'
    | '/matricula'
    | '/meu-plano'
    | '/notificacoes'
    | '/planos'
    | '/presenca'
    | '/primeiro-acesso'
    | '/professores'
    | '/trocar-senha'
    | '/turmas'
    | '/reset-password/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/aula-experimental'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/forgot-password'
    | '/login'
    | '/matricula'
    | '/meu-plano'
    | '/notificacoes'
    | '/planos'
    | '/presenca'
    | '/primeiro-acesso'
    | '/professores'
    | '/trocar-senha'
    | '/turmas'
    | '/reset-password/$token'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/aula-experimental'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/forgot-password'
    | '/login'
    | '/matricula'
    | '/meu-plano'
    | '/notificacoes'
    | '/planos'
    | '/presenca'
    | '/primeiro-acesso'
    | '/professores'
    | '/trocar-senha'
    | '/turmas'
    | '/reset-password/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  AulaExperimentalRoute: typeof AulaExperimentalRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MatriculaRoute: typeof MatriculaRoute
  MeuPlanoRoute: typeof MeuPlanoRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PlanosRoute: typeof PlanosRoute
  PresencaRoute: typeof PresencaRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  ProfessoresRoute: typeof ProfessoresRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  TurmasRoute: typeof TurmasRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores': {
      id: '/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof ProfessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenca': {
      id: '/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof PresencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-plano': {
      id: '/meu-plano'
      path: '/meu-plano'
      fullPath: '/meu-plano'
      preLoaderRoute: typeof MeuPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula-experimental': {
      id: '/aula-experimental'
      path: '/aula-experimental'
      fullPath: '/aula-experimental'
      preLoaderRoute: typeof AulaExperimentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  AulaExperimentalRoute: AulaExperimentalRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRoute,
  FinanceiroRoute: FinanceiroRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MatriculaRoute: MatriculaRoute,
  MeuPlanoRoute: MeuPlanoRoute,
  NotificacoesRoute: NotificacoesRoute,
  PlanosRoute: PlanosRoute,
  PresencaRoute: PresencaRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  ProfessoresRoute: ProfessoresRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  TurmasRoute: TurmasRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
