/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as ProfessoresRouteImport } from './routes/professores'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as PresencasRouteImport } from './routes/presencas'
import { Route as PresencaRouteImport } from './routes/presenca'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MeuPlanoRouteImport } from './routes/meu-plano'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CampeonatosRouteImport } from './routes/campeonatos'
import { Route as AulaExperimentalRouteImport } from './routes/aula-experimental'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorIndexRouteImport } from './routes/professor/index'
import { Route as PortalResponsavelIndexRouteImport } from './routes/portal-responsavel/index'
import { Route as PortalAlunoIndexRouteImport } from './routes/portal-aluno/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ProfessorPresencasRouteImport } from './routes/professor/presencas'
import { Route as PortalResponsavelPresencasRouteImport } from './routes/portal-responsavel/presencas'
import { Route as PortalResponsavelPerfilRouteImport } from './routes/portal-responsavel/perfil'
import { Route as PortalResponsavelNotificacoesRouteImport } from './routes/portal-responsavel/notificacoes'
import { Route as PortalResponsavelMeusFilhosRouteImport } from './routes/portal-responsavel/meus-filhos'
import { Route as PortalResponsavelFinanceiroRouteImport } from './routes/portal-responsavel/financeiro'
import { Route as PortalResponsavelDashboardRouteImport } from './routes/portal-responsavel/dashboard'
import { Route as PortalResponsavelContratoRouteImport } from './routes/portal-responsavel/contrato'
import { Route as PortalResponsavelConfiguracoesRouteImport } from './routes/portal-responsavel/configuracoes'
import { Route as PortalResponsavelAgendaRouteImport } from './routes/portal-responsavel/agenda'
import { Route as PortalAlunoTreinosRouteImport } from './routes/portal-aluno/treinos'
import { Route as PortalAlunoPresencasRouteImport } from './routes/portal-aluno/presencas'
import { Route as PortalAlunoPerfilRouteImport } from './routes/portal-aluno/perfil'
import { Route as PortalAlunoNotificacoesRouteImport } from './routes/portal-aluno/notificacoes'
import { Route as PortalAlunoMeuPlanoRouteImport } from './routes/portal-aluno/meu-plano'
import { Route as PortalAlunoFinanceiroRouteImport } from './routes/portal-aluno/financeiro'
import { Route as PortalAlunoDashboardRouteImport } from './routes/portal-aluno/dashboard'
import { Route as PortalAlunoContratoRouteImport } from './routes/portal-aluno/contrato'
import { Route as PortalAlunoConfiguracoesRouteImport } from './routes/portal-aluno/configuracoes'
import { Route as PortalAlunoCarteirinhaRouteImport } from './routes/portal-aluno/carteirinha'
import { Route as PortalAlunoAvaliacoesRouteImport } from './routes/portal-aluno/avaliacoes'
import { Route as PortalAlunoAgendaRouteImport } from './routes/portal-aluno/agenda'
import { Route as CampeonatosChampionshipIdRouteImport } from './routes/campeonatos.$championshipId'
import { Route as AdminQuadrasRouteImport } from './routes/admin/quadras'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminCommandCenterStudentsPreviewRouteImport } from './routes/admin/command-center-students-preview'
import { Route as AdminCommandCenterPreviewRouteImport } from './routes/admin/command-center-preview'
import { Route as AdminCommandCenterFinancialPreviewRouteImport } from './routes/admin/command-center-financial-preview'
import { Route as AdminCommandCenterEnrollmentPreviewRouteImport } from './routes/admin/command-center-enrollment-preview'
import { Route as AdminCampeonatosRouteImport } from './routes/admin/campeonatos'
import { Route as AdminBiRouteImport } from './routes/admin/bi'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as DashboardAlunoIdRouteImport } from './routes/dashboard/aluno.$id'
import { Route as AdminCampeonatosInscricoesRouteImport } from './routes/admin/campeonatos.inscricoes'
import { Route as AdminBiTurmasRouteImport } from './routes/admin/bi.turmas'
import { Route as AdminBiRelatoriosRouteImport } from './routes/admin/bi.relatorios'
import { Route as AdminBiQuadrasRouteImport } from './routes/admin/bi.quadras'
import { Route as AdminBiInsightsRouteImport } from './routes/admin/bi.insights'
import { Route as AdminBiInadimplenciaRouteImport } from './routes/admin/bi.inadimplencia'
import { Route as AdminBiFinanceiroRouteImport } from './routes/admin/bi.financeiro'
import { Route as AdminBiCampeonatosRouteImport } from './routes/admin/bi.campeonatos'
import { Route as AdminBiAlunosRouteImport } from './routes/admin/bi.alunos'
import { Route as AdminFinanceiroAutomacoesHistoricoRouteImport } from './routes/admin/financeiro.automacoes.historico'
import { Route as AdminCampeonatosChampionshipIdRodadasRouteImport } from './routes/admin/campeonatos.$championshipId.rodadas'
import { Route as AdminCampeonatosChampionshipIdMataMataRouteImport } from './routes/admin/campeonatos.$championshipId.mata-mata'
import { Route as AdminCampeonatosChampionshipIdGruposRouteImport } from './routes/admin/campeonatos.$championshipId.grupos'
import { Route as AdminCampeonatosChampionshipIdEstatisticasRouteImport } from './routes/admin/campeonatos.$championshipId.estatisticas'
import { Route as AdminCampeonatosChampionshipIdClassificacaoRouteImport } from './routes/admin/campeonatos.$championshipId.classificacao'
import { Route as AdminCampeonatosInscricoesRegistrationIdAtletasRouteImport } from './routes/admin/campeonatos.inscricoes.$registrationId.atletas'
import { Route as AdminCampeonatosChampionshipIdJogosMatchIdSumulaRouteImport } from './routes/admin/campeonatos.$championshipId.jogos.$matchId.sumula'

const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessoresRoute = ProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencasRoute = PresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencaRoute = PresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPlanoRoute = MeuPlanoRouteImport.update({
  id: '/meu-plano',
  path: '/meu-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosRoute = CampeonatosRouteImport.update({
  id: '/campeonatos',
  path: '/campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaExperimentalRoute = AulaExperimentalRouteImport.update({
  id: '/aula-experimental',
  path: '/aula-experimental',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/professor/',
  path: '/professor/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResponsavelIndexRoute = PortalResponsavelIndexRouteImport.update({
  id: '/portal-responsavel/',
  path: '/portal-responsavel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoIndexRoute = PortalAlunoIndexRouteImport.update({
  id: '/portal-aluno/',
  path: '/portal-aluno/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorPresencasRoute = ProfessorPresencasRouteImport.update({
  id: '/professor/presencas',
  path: '/professor/presencas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResponsavelPresencasRoute =
  PortalResponsavelPresencasRouteImport.update({
    id: '/portal-responsavel/presencas',
    path: '/portal-responsavel/presencas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalResponsavelPerfilRoute = PortalResponsavelPerfilRouteImport.update({
  id: '/portal-responsavel/perfil',
  path: '/portal-responsavel/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalResponsavelNotificacoesRoute =
  PortalResponsavelNotificacoesRouteImport.update({
    id: '/portal-responsavel/notificacoes',
    path: '/portal-responsavel/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalResponsavelMeusFilhosRoute =
  PortalResponsavelMeusFilhosRouteImport.update({
    id: '/portal-responsavel/meus-filhos',
    path: '/portal-responsavel/meus-filhos',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalResponsavelFinanceiroRoute =
  PortalResponsavelFinanceiroRouteImport.update({
    id: '/portal-responsavel/financeiro',
    path: '/portal-responsavel/financeiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalResponsavelDashboardRoute =
  PortalResponsavelDashboardRouteImport.update({
    id: '/portal-responsavel/dashboard',
    path: '/portal-responsavel/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalResponsavelContratoRoute =
  PortalResponsavelContratoRouteImport.update({
    id: '/portal-responsavel/contrato',
    path: '/portal-responsavel/contrato',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalResponsavelConfiguracoesRoute =
  PortalResponsavelConfiguracoesRouteImport.update({
    id: '/portal-responsavel/configuracoes',
    path: '/portal-responsavel/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalResponsavelAgendaRoute = PortalResponsavelAgendaRouteImport.update({
  id: '/portal-responsavel/agenda',
  path: '/portal-responsavel/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoTreinosRoute = PortalAlunoTreinosRouteImport.update({
  id: '/portal-aluno/treinos',
  path: '/portal-aluno/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoPresencasRoute = PortalAlunoPresencasRouteImport.update({
  id: '/portal-aluno/presencas',
  path: '/portal-aluno/presencas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoPerfilRoute = PortalAlunoPerfilRouteImport.update({
  id: '/portal-aluno/perfil',
  path: '/portal-aluno/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoNotificacoesRoute = PortalAlunoNotificacoesRouteImport.update({
  id: '/portal-aluno/notificacoes',
  path: '/portal-aluno/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoMeuPlanoRoute = PortalAlunoMeuPlanoRouteImport.update({
  id: '/portal-aluno/meu-plano',
  path: '/portal-aluno/meu-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoFinanceiroRoute = PortalAlunoFinanceiroRouteImport.update({
  id: '/portal-aluno/financeiro',
  path: '/portal-aluno/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoDashboardRoute = PortalAlunoDashboardRouteImport.update({
  id: '/portal-aluno/dashboard',
  path: '/portal-aluno/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoContratoRoute = PortalAlunoContratoRouteImport.update({
  id: '/portal-aluno/contrato',
  path: '/portal-aluno/contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoConfiguracoesRoute =
  PortalAlunoConfiguracoesRouteImport.update({
    id: '/portal-aluno/configuracoes',
    path: '/portal-aluno/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalAlunoCarteirinhaRoute = PortalAlunoCarteirinhaRouteImport.update({
  id: '/portal-aluno/carteirinha',
  path: '/portal-aluno/carteirinha',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoAvaliacoesRoute = PortalAlunoAvaliacoesRouteImport.update({
  id: '/portal-aluno/avaliacoes',
  path: '/portal-aluno/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoAgendaRoute = PortalAlunoAgendaRouteImport.update({
  id: '/portal-aluno/agenda',
  path: '/portal-aluno/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosChampionshipIdRoute =
  CampeonatosChampionshipIdRouteImport.update({
    id: '/$championshipId',
    path: '/$championshipId',
    getParentRoute: () => CampeonatosRoute,
  } as any)
const AdminQuadrasRoute = AdminQuadrasRouteImport.update({
  id: '/admin/quadras',
  path: '/admin/quadras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/admin/enrollments',
  path: '/admin/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandCenterStudentsPreviewRoute =
  AdminCommandCenterStudentsPreviewRouteImport.update({
    id: '/admin/command-center-students-preview',
    path: '/admin/command-center-students-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCommandCenterPreviewRoute =
  AdminCommandCenterPreviewRouteImport.update({
    id: '/admin/command-center-preview',
    path: '/admin/command-center-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCommandCenterFinancialPreviewRoute =
  AdminCommandCenterFinancialPreviewRouteImport.update({
    id: '/admin/command-center-financial-preview',
    path: '/admin/command-center-financial-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCommandCenterEnrollmentPreviewRoute =
  AdminCommandCenterEnrollmentPreviewRouteImport.update({
    id: '/admin/command-center-enrollment-preview',
    path: '/admin/command-center-enrollment-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCampeonatosRoute = AdminCampeonatosRouteImport.update({
  id: '/admin/campeonatos',
  path: '/admin/campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBiRoute = AdminBiRouteImport.update({
  id: '/admin/bi',
  path: '/admin/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/admin/agenda',
  path: '/admin/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlunoIdRoute = DashboardAlunoIdRouteImport.update({
  id: '/aluno/$id',
  path: '/aluno/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCampeonatosInscricoesRoute =
  AdminCampeonatosInscricoesRouteImport.update({
    id: '/inscricoes',
    path: '/inscricoes',
    getParentRoute: () => AdminCampeonatosRoute,
  } as any)
const AdminBiTurmasRoute = AdminBiTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminBiRelatoriosRoute = AdminBiRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminBiQuadrasRoute = AdminBiQuadrasRouteImport.update({
  id: '/quadras',
  path: '/quadras',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminBiInsightsRoute = AdminBiInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminBiInadimplenciaRoute = AdminBiInadimplenciaRouteImport.update({
  id: '/inadimplencia',
  path: '/inadimplencia',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminBiFinanceiroRoute = AdminBiFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminBiCampeonatosRoute = AdminBiCampeonatosRouteImport.update({
  id: '/campeonatos',
  path: '/campeonatos',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminBiAlunosRoute = AdminBiAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminBiRoute,
} as any)
const AdminFinanceiroAutomacoesHistoricoRoute =
  AdminFinanceiroAutomacoesHistoricoRouteImport.update({
    id: '/automacoes/historico',
    path: '/automacoes/historico',
    getParentRoute: () => AdminFinanceiroRoute,
  } as any)
const AdminCampeonatosChampionshipIdRodadasRoute =
  AdminCampeonatosChampionshipIdRodadasRouteImport.update({
    id: '/$championshipId/rodadas',
    path: '/$championshipId/rodadas',
    getParentRoute: () => AdminCampeonatosRoute,
  } as any)
const AdminCampeonatosChampionshipIdMataMataRoute =
  AdminCampeonatosChampionshipIdMataMataRouteImport.update({
    id: '/$championshipId/mata-mata',
    path: '/$championshipId/mata-mata',
    getParentRoute: () => AdminCampeonatosRoute,
  } as any)
const AdminCampeonatosChampionshipIdGruposRoute =
  AdminCampeonatosChampionshipIdGruposRouteImport.update({
    id: '/$championshipId/grupos',
    path: '/$championshipId/grupos',
    getParentRoute: () => AdminCampeonatosRoute,
  } as any)
const AdminCampeonatosChampionshipIdEstatisticasRoute =
  AdminCampeonatosChampionshipIdEstatisticasRouteImport.update({
    id: '/$championshipId/estatisticas',
    path: '/$championshipId/estatisticas',
    getParentRoute: () => AdminCampeonatosRoute,
  } as any)
const AdminCampeonatosChampionshipIdClassificacaoRoute =
  AdminCampeonatosChampionshipIdClassificacaoRouteImport.update({
    id: '/$championshipId/classificacao',
    path: '/$championshipId/classificacao',
    getParentRoute: () => AdminCampeonatosRoute,
  } as any)
const AdminCampeonatosInscricoesRegistrationIdAtletasRoute =
  AdminCampeonatosInscricoesRegistrationIdAtletasRouteImport.update({
    id: '/$registrationId/atletas',
    path: '/$registrationId/atletas',
    getParentRoute: () => AdminCampeonatosInscricoesRoute,
  } as any)
const AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute =
  AdminCampeonatosChampionshipIdJogosMatchIdSumulaRouteImport.update({
    id: '/$championshipId/jogos/$matchId/sumula',
    path: '/$championshipId/jogos/$matchId/sumula',
    getParentRoute: () => AdminCampeonatosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/aula-experimental': typeof AulaExperimentalRoute
  '/campeonatos': typeof CampeonatosRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/presenca': typeof PresencaRoute
  '/presencas': typeof PresencasRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/professores': typeof ProfessoresRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/turmas': typeof TurmasRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/bi': typeof AdminBiRouteWithChildren
  '/admin/campeonatos': typeof AdminCampeonatosRouteWithChildren
  '/admin/command-center-enrollment-preview': typeof AdminCommandCenterEnrollmentPreviewRoute
  '/admin/command-center-financial-preview': typeof AdminCommandCenterFinancialPreviewRoute
  '/admin/command-center-preview': typeof AdminCommandCenterPreviewRoute
  '/admin/command-center-students-preview': typeof AdminCommandCenterStudentsPreviewRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/quadras': typeof AdminQuadrasRoute
  '/campeonatos/$championshipId': typeof CampeonatosChampionshipIdRoute
  '/portal-aluno/agenda': typeof PortalAlunoAgendaRoute
  '/portal-aluno/avaliacoes': typeof PortalAlunoAvaliacoesRoute
  '/portal-aluno/carteirinha': typeof PortalAlunoCarteirinhaRoute
  '/portal-aluno/configuracoes': typeof PortalAlunoConfiguracoesRoute
  '/portal-aluno/contrato': typeof PortalAlunoContratoRoute
  '/portal-aluno/dashboard': typeof PortalAlunoDashboardRoute
  '/portal-aluno/financeiro': typeof PortalAlunoFinanceiroRoute
  '/portal-aluno/meu-plano': typeof PortalAlunoMeuPlanoRoute
  '/portal-aluno/notificacoes': typeof PortalAlunoNotificacoesRoute
  '/portal-aluno/perfil': typeof PortalAlunoPerfilRoute
  '/portal-aluno/presencas': typeof PortalAlunoPresencasRoute
  '/portal-aluno/treinos': typeof PortalAlunoTreinosRoute
  '/portal-responsavel/agenda': typeof PortalResponsavelAgendaRoute
  '/portal-responsavel/configuracoes': typeof PortalResponsavelConfiguracoesRoute
  '/portal-responsavel/contrato': typeof PortalResponsavelContratoRoute
  '/portal-responsavel/dashboard': typeof PortalResponsavelDashboardRoute
  '/portal-responsavel/financeiro': typeof PortalResponsavelFinanceiroRoute
  '/portal-responsavel/meus-filhos': typeof PortalResponsavelMeusFilhosRoute
  '/portal-responsavel/notificacoes': typeof PortalResponsavelNotificacoesRoute
  '/portal-responsavel/perfil': typeof PortalResponsavelPerfilRoute
  '/portal-responsavel/presencas': typeof PortalResponsavelPresencasRoute
  '/professor/presencas': typeof ProfessorPresencasRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/portal-aluno/': typeof PortalAlunoIndexRoute
  '/portal-responsavel/': typeof PortalResponsavelIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/admin/bi/alunos': typeof AdminBiAlunosRoute
  '/admin/bi/campeonatos': typeof AdminBiCampeonatosRoute
  '/admin/bi/financeiro': typeof AdminBiFinanceiroRoute
  '/admin/bi/inadimplencia': typeof AdminBiInadimplenciaRoute
  '/admin/bi/insights': typeof AdminBiInsightsRoute
  '/admin/bi/quadras': typeof AdminBiQuadrasRoute
  '/admin/bi/relatorios': typeof AdminBiRelatoriosRoute
  '/admin/bi/turmas': typeof AdminBiTurmasRoute
  '/admin/campeonatos/inscricoes': typeof AdminCampeonatosInscricoesRouteWithChildren
  '/dashboard/aluno/$id': typeof DashboardAlunoIdRoute
  '/admin/campeonatos/$championshipId/classificacao': typeof AdminCampeonatosChampionshipIdClassificacaoRoute
  '/admin/campeonatos/$championshipId/estatisticas': typeof AdminCampeonatosChampionshipIdEstatisticasRoute
  '/admin/campeonatos/$championshipId/grupos': typeof AdminCampeonatosChampionshipIdGruposRoute
  '/admin/campeonatos/$championshipId/mata-mata': typeof AdminCampeonatosChampionshipIdMataMataRoute
  '/admin/campeonatos/$championshipId/rodadas': typeof AdminCampeonatosChampionshipIdRodadasRoute
  '/admin/financeiro/automacoes/historico': typeof AdminFinanceiroAutomacoesHistoricoRoute
  '/admin/campeonatos/inscricoes/$registrationId/atletas': typeof AdminCampeonatosInscricoesRegistrationIdAtletasRoute
  '/admin/campeonatos/$championshipId/jogos/$matchId/sumula': typeof AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/aula-experimental': typeof AulaExperimentalRoute
  '/campeonatos': typeof CampeonatosRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/presenca': typeof PresencaRoute
  '/presencas': typeof PresencasRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/professores': typeof ProfessoresRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/turmas': typeof TurmasRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/bi': typeof AdminBiRouteWithChildren
  '/admin/campeonatos': typeof AdminCampeonatosRouteWithChildren
  '/admin/command-center-enrollment-preview': typeof AdminCommandCenterEnrollmentPreviewRoute
  '/admin/command-center-financial-preview': typeof AdminCommandCenterFinancialPreviewRoute
  '/admin/command-center-preview': typeof AdminCommandCenterPreviewRoute
  '/admin/command-center-students-preview': typeof AdminCommandCenterStudentsPreviewRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/quadras': typeof AdminQuadrasRoute
  '/campeonatos/$championshipId': typeof CampeonatosChampionshipIdRoute
  '/portal-aluno/agenda': typeof PortalAlunoAgendaRoute
  '/portal-aluno/avaliacoes': typeof PortalAlunoAvaliacoesRoute
  '/portal-aluno/carteirinha': typeof PortalAlunoCarteirinhaRoute
  '/portal-aluno/configuracoes': typeof PortalAlunoConfiguracoesRoute
  '/portal-aluno/contrato': typeof PortalAlunoContratoRoute
  '/portal-aluno/dashboard': typeof PortalAlunoDashboardRoute
  '/portal-aluno/financeiro': typeof PortalAlunoFinanceiroRoute
  '/portal-aluno/meu-plano': typeof PortalAlunoMeuPlanoRoute
  '/portal-aluno/notificacoes': typeof PortalAlunoNotificacoesRoute
  '/portal-aluno/perfil': typeof PortalAlunoPerfilRoute
  '/portal-aluno/presencas': typeof PortalAlunoPresencasRoute
  '/portal-aluno/treinos': typeof PortalAlunoTreinosRoute
  '/portal-responsavel/agenda': typeof PortalResponsavelAgendaRoute
  '/portal-responsavel/configuracoes': typeof PortalResponsavelConfiguracoesRoute
  '/portal-responsavel/contrato': typeof PortalResponsavelContratoRoute
  '/portal-responsavel/dashboard': typeof PortalResponsavelDashboardRoute
  '/portal-responsavel/financeiro': typeof PortalResponsavelFinanceiroRoute
  '/portal-responsavel/meus-filhos': typeof PortalResponsavelMeusFilhosRoute
  '/portal-responsavel/notificacoes': typeof PortalResponsavelNotificacoesRoute
  '/portal-responsavel/perfil': typeof PortalResponsavelPerfilRoute
  '/portal-responsavel/presencas': typeof PortalResponsavelPresencasRoute
  '/professor/presencas': typeof ProfessorPresencasRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/portal-aluno': typeof PortalAlunoIndexRoute
  '/portal-responsavel': typeof PortalResponsavelIndexRoute
  '/professor': typeof ProfessorIndexRoute
  '/admin/bi/alunos': typeof AdminBiAlunosRoute
  '/admin/bi/campeonatos': typeof AdminBiCampeonatosRoute
  '/admin/bi/financeiro': typeof AdminBiFinanceiroRoute
  '/admin/bi/inadimplencia': typeof AdminBiInadimplenciaRoute
  '/admin/bi/insights': typeof AdminBiInsightsRoute
  '/admin/bi/quadras': typeof AdminBiQuadrasRoute
  '/admin/bi/relatorios': typeof AdminBiRelatoriosRoute
  '/admin/bi/turmas': typeof AdminBiTurmasRoute
  '/admin/campeonatos/inscricoes': typeof AdminCampeonatosInscricoesRouteWithChildren
  '/dashboard/aluno/$id': typeof DashboardAlunoIdRoute
  '/admin/campeonatos/$championshipId/classificacao': typeof AdminCampeonatosChampionshipIdClassificacaoRoute
  '/admin/campeonatos/$championshipId/estatisticas': typeof AdminCampeonatosChampionshipIdEstatisticasRoute
  '/admin/campeonatos/$championshipId/grupos': typeof AdminCampeonatosChampionshipIdGruposRoute
  '/admin/campeonatos/$championshipId/mata-mata': typeof AdminCampeonatosChampionshipIdMataMataRoute
  '/admin/campeonatos/$championshipId/rodadas': typeof AdminCampeonatosChampionshipIdRodadasRoute
  '/admin/financeiro/automacoes/historico': typeof AdminFinanceiroAutomacoesHistoricoRoute
  '/admin/campeonatos/inscricoes/$registrationId/atletas': typeof AdminCampeonatosInscricoesRegistrationIdAtletasRoute
  '/admin/campeonatos/$championshipId/jogos/$matchId/sumula': typeof AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/aula-experimental': typeof AulaExperimentalRoute
  '/campeonatos': typeof CampeonatosRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/matricula': typeof MatriculaRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/presenca': typeof PresencaRoute
  '/presencas': typeof PresencasRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/professores': typeof ProfessoresRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/turmas': typeof TurmasRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/bi': typeof AdminBiRouteWithChildren
  '/admin/campeonatos': typeof AdminCampeonatosRouteWithChildren
  '/admin/command-center-enrollment-preview': typeof AdminCommandCenterEnrollmentPreviewRoute
  '/admin/command-center-financial-preview': typeof AdminCommandCenterFinancialPreviewRoute
  '/admin/command-center-preview': typeof AdminCommandCenterPreviewRoute
  '/admin/command-center-students-preview': typeof AdminCommandCenterStudentsPreviewRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/quadras': typeof AdminQuadrasRoute
  '/campeonatos/$championshipId': typeof CampeonatosChampionshipIdRoute
  '/portal-aluno/agenda': typeof PortalAlunoAgendaRoute
  '/portal-aluno/avaliacoes': typeof PortalAlunoAvaliacoesRoute
  '/portal-aluno/carteirinha': typeof PortalAlunoCarteirinhaRoute
  '/portal-aluno/configuracoes': typeof PortalAlunoConfiguracoesRoute
  '/portal-aluno/contrato': typeof PortalAlunoContratoRoute
  '/portal-aluno/dashboard': typeof PortalAlunoDashboardRoute
  '/portal-aluno/financeiro': typeof PortalAlunoFinanceiroRoute
  '/portal-aluno/meu-plano': typeof PortalAlunoMeuPlanoRoute
  '/portal-aluno/notificacoes': typeof PortalAlunoNotificacoesRoute
  '/portal-aluno/perfil': typeof PortalAlunoPerfilRoute
  '/portal-aluno/presencas': typeof PortalAlunoPresencasRoute
  '/portal-aluno/treinos': typeof PortalAlunoTreinosRoute
  '/portal-responsavel/agenda': typeof PortalResponsavelAgendaRoute
  '/portal-responsavel/configuracoes': typeof PortalResponsavelConfiguracoesRoute
  '/portal-responsavel/contrato': typeof PortalResponsavelContratoRoute
  '/portal-responsavel/dashboard': typeof PortalResponsavelDashboardRoute
  '/portal-responsavel/financeiro': typeof PortalResponsavelFinanceiroRoute
  '/portal-responsavel/meus-filhos': typeof PortalResponsavelMeusFilhosRoute
  '/portal-responsavel/notificacoes': typeof PortalResponsavelNotificacoesRoute
  '/portal-responsavel/perfil': typeof PortalResponsavelPerfilRoute
  '/portal-responsavel/presencas': typeof PortalResponsavelPresencasRoute
  '/professor/presencas': typeof ProfessorPresencasRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/portal-aluno/': typeof PortalAlunoIndexRoute
  '/portal-responsavel/': typeof PortalResponsavelIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/admin/bi/alunos': typeof AdminBiAlunosRoute
  '/admin/bi/campeonatos': typeof AdminBiCampeonatosRoute
  '/admin/bi/financeiro': typeof AdminBiFinanceiroRoute
  '/admin/bi/inadimplencia': typeof AdminBiInadimplenciaRoute
  '/admin/bi/insights': typeof AdminBiInsightsRoute
  '/admin/bi/quadras': typeof AdminBiQuadrasRoute
  '/admin/bi/relatorios': typeof AdminBiRelatoriosRoute
  '/admin/bi/turmas': typeof AdminBiTurmasRoute
  '/admin/campeonatos/inscricoes': typeof AdminCampeonatosInscricoesRouteWithChildren
  '/dashboard/aluno/$id': typeof DashboardAlunoIdRoute
  '/admin/campeonatos/$championshipId/classificacao': typeof AdminCampeonatosChampionshipIdClassificacaoRoute
  '/admin/campeonatos/$championshipId/estatisticas': typeof AdminCampeonatosChampionshipIdEstatisticasRoute
  '/admin/campeonatos/$championshipId/grupos': typeof AdminCampeonatosChampionshipIdGruposRoute
  '/admin/campeonatos/$championshipId/mata-mata': typeof AdminCampeonatosChampionshipIdMataMataRoute
  '/admin/campeonatos/$championshipId/rodadas': typeof AdminCampeonatosChampionshipIdRodadasRoute
  '/admin/financeiro/automacoes/historico': typeof AdminFinanceiroAutomacoesHistoricoRoute
  '/admin/campeonatos/inscricoes/$registrationId/atletas': typeof AdminCampeonatosInscricoesRegistrationIdAtletasRoute
  '/admin/campeonatos/$championshipId/jogos/$matchId/sumula': typeof AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alunos'
    | '/aula-experimental'
    | '/campeonatos'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/forgot-password'
    | '/login'
    | '/matricula'
    | '/meu-plano'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/presenca'
    | '/presencas'
    | '/primeiro-acesso'
    | '/professores'
    | '/trocar-senha'
    | '/turmas'
    | '/admin/agenda'
    | '/admin/bi'
    | '/admin/campeonatos'
    | '/admin/command-center-enrollment-preview'
    | '/admin/command-center-financial-preview'
    | '/admin/command-center-preview'
    | '/admin/command-center-students-preview'
    | '/admin/enrollments'
    | '/admin/financeiro'
    | '/admin/quadras'
    | '/campeonatos/$championshipId'
    | '/portal-aluno/agenda'
    | '/portal-aluno/avaliacoes'
    | '/portal-aluno/carteirinha'
    | '/portal-aluno/configuracoes'
    | '/portal-aluno/contrato'
    | '/portal-aluno/dashboard'
    | '/portal-aluno/financeiro'
    | '/portal-aluno/meu-plano'
    | '/portal-aluno/notificacoes'
    | '/portal-aluno/perfil'
    | '/portal-aluno/presencas'
    | '/portal-aluno/treinos'
    | '/portal-responsavel/agenda'
    | '/portal-responsavel/configuracoes'
    | '/portal-responsavel/contrato'
    | '/portal-responsavel/dashboard'
    | '/portal-responsavel/financeiro'
    | '/portal-responsavel/meus-filhos'
    | '/portal-responsavel/notificacoes'
    | '/portal-responsavel/perfil'
    | '/portal-responsavel/presencas'
    | '/professor/presencas'
    | '/reset-password/$token'
    | '/portal-aluno/'
    | '/portal-responsavel/'
    | '/professor/'
    | '/admin/bi/alunos'
    | '/admin/bi/campeonatos'
    | '/admin/bi/financeiro'
    | '/admin/bi/inadimplencia'
    | '/admin/bi/insights'
    | '/admin/bi/quadras'
    | '/admin/bi/relatorios'
    | '/admin/bi/turmas'
    | '/admin/campeonatos/inscricoes'
    | '/dashboard/aluno/$id'
    | '/admin/campeonatos/$championshipId/classificacao'
    | '/admin/campeonatos/$championshipId/estatisticas'
    | '/admin/campeonatos/$championshipId/grupos'
    | '/admin/campeonatos/$championshipId/mata-mata'
    | '/admin/campeonatos/$championshipId/rodadas'
    | '/admin/financeiro/automacoes/historico'
    | '/admin/campeonatos/inscricoes/$registrationId/atletas'
    | '/admin/campeonatos/$championshipId/jogos/$matchId/sumula'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alunos'
    | '/aula-experimental'
    | '/campeonatos'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/forgot-password'
    | '/login'
    | '/matricula'
    | '/meu-plano'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/presenca'
    | '/presencas'
    | '/primeiro-acesso'
    | '/professores'
    | '/trocar-senha'
    | '/turmas'
    | '/admin/agenda'
    | '/admin/bi'
    | '/admin/campeonatos'
    | '/admin/command-center-enrollment-preview'
    | '/admin/command-center-financial-preview'
    | '/admin/command-center-preview'
    | '/admin/command-center-students-preview'
    | '/admin/enrollments'
    | '/admin/financeiro'
    | '/admin/quadras'
    | '/campeonatos/$championshipId'
    | '/portal-aluno/agenda'
    | '/portal-aluno/avaliacoes'
    | '/portal-aluno/carteirinha'
    | '/portal-aluno/configuracoes'
    | '/portal-aluno/contrato'
    | '/portal-aluno/dashboard'
    | '/portal-aluno/financeiro'
    | '/portal-aluno/meu-plano'
    | '/portal-aluno/notificacoes'
    | '/portal-aluno/perfil'
    | '/portal-aluno/presencas'
    | '/portal-aluno/treinos'
    | '/portal-responsavel/agenda'
    | '/portal-responsavel/configuracoes'
    | '/portal-responsavel/contrato'
    | '/portal-responsavel/dashboard'
    | '/portal-responsavel/financeiro'
    | '/portal-responsavel/meus-filhos'
    | '/portal-responsavel/notificacoes'
    | '/portal-responsavel/perfil'
    | '/portal-responsavel/presencas'
    | '/professor/presencas'
    | '/reset-password/$token'
    | '/portal-aluno'
    | '/portal-responsavel'
    | '/professor'
    | '/admin/bi/alunos'
    | '/admin/bi/campeonatos'
    | '/admin/bi/financeiro'
    | '/admin/bi/inadimplencia'
    | '/admin/bi/insights'
    | '/admin/bi/quadras'
    | '/admin/bi/relatorios'
    | '/admin/bi/turmas'
    | '/admin/campeonatos/inscricoes'
    | '/dashboard/aluno/$id'
    | '/admin/campeonatos/$championshipId/classificacao'
    | '/admin/campeonatos/$championshipId/estatisticas'
    | '/admin/campeonatos/$championshipId/grupos'
    | '/admin/campeonatos/$championshipId/mata-mata'
    | '/admin/campeonatos/$championshipId/rodadas'
    | '/admin/financeiro/automacoes/historico'
    | '/admin/campeonatos/inscricoes/$registrationId/atletas'
    | '/admin/campeonatos/$championshipId/jogos/$matchId/sumula'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alunos'
    | '/aula-experimental'
    | '/campeonatos'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/financeiro'
    | '/forgot-password'
    | '/login'
    | '/matricula'
    | '/meu-plano'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/presenca'
    | '/presencas'
    | '/primeiro-acesso'
    | '/professores'
    | '/trocar-senha'
    | '/turmas'
    | '/admin/agenda'
    | '/admin/bi'
    | '/admin/campeonatos'
    | '/admin/command-center-enrollment-preview'
    | '/admin/command-center-financial-preview'
    | '/admin/command-center-preview'
    | '/admin/command-center-students-preview'
    | '/admin/enrollments'
    | '/admin/financeiro'
    | '/admin/quadras'
    | '/campeonatos/$championshipId'
    | '/portal-aluno/agenda'
    | '/portal-aluno/avaliacoes'
    | '/portal-aluno/carteirinha'
    | '/portal-aluno/configuracoes'
    | '/portal-aluno/contrato'
    | '/portal-aluno/dashboard'
    | '/portal-aluno/financeiro'
    | '/portal-aluno/meu-plano'
    | '/portal-aluno/notificacoes'
    | '/portal-aluno/perfil'
    | '/portal-aluno/presencas'
    | '/portal-aluno/treinos'
    | '/portal-responsavel/agenda'
    | '/portal-responsavel/configuracoes'
    | '/portal-responsavel/contrato'
    | '/portal-responsavel/dashboard'
    | '/portal-responsavel/financeiro'
    | '/portal-responsavel/meus-filhos'
    | '/portal-responsavel/notificacoes'
    | '/portal-responsavel/perfil'
    | '/portal-responsavel/presencas'
    | '/professor/presencas'
    | '/reset-password/$token'
    | '/portal-aluno/'
    | '/portal-responsavel/'
    | '/professor/'
    | '/admin/bi/alunos'
    | '/admin/bi/campeonatos'
    | '/admin/bi/financeiro'
    | '/admin/bi/inadimplencia'
    | '/admin/bi/insights'
    | '/admin/bi/quadras'
    | '/admin/bi/relatorios'
    | '/admin/bi/turmas'
    | '/admin/campeonatos/inscricoes'
    | '/dashboard/aluno/$id'
    | '/admin/campeonatos/$championshipId/classificacao'
    | '/admin/campeonatos/$championshipId/estatisticas'
    | '/admin/campeonatos/$championshipId/grupos'
    | '/admin/campeonatos/$championshipId/mata-mata'
    | '/admin/campeonatos/$championshipId/rodadas'
    | '/admin/financeiro/automacoes/historico'
    | '/admin/campeonatos/inscricoes/$registrationId/atletas'
    | '/admin/campeonatos/$championshipId/jogos/$matchId/sumula'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlunosRoute: typeof AlunosRoute
  AulaExperimentalRoute: typeof AulaExperimentalRoute
  CampeonatosRoute: typeof CampeonatosRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MatriculaRoute: typeof MatriculaRoute
  MeuPlanoRoute: typeof MeuPlanoRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PresencaRoute: typeof PresencaRoute
  PresencasRoute: typeof PresencasRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  ProfessoresRoute: typeof ProfessoresRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  TurmasRoute: typeof TurmasRoute
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminBiRoute: typeof AdminBiRouteWithChildren
  AdminCampeonatosRoute: typeof AdminCampeonatosRouteWithChildren
  AdminCommandCenterEnrollmentPreviewRoute: typeof AdminCommandCenterEnrollmentPreviewRoute
  AdminCommandCenterFinancialPreviewRoute: typeof AdminCommandCenterFinancialPreviewRoute
  AdminCommandCenterPreviewRoute: typeof AdminCommandCenterPreviewRoute
  AdminCommandCenterStudentsPreviewRoute: typeof AdminCommandCenterStudentsPreviewRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRouteWithChildren
  AdminQuadrasRoute: typeof AdminQuadrasRoute
  PortalAlunoAgendaRoute: typeof PortalAlunoAgendaRoute
  PortalAlunoAvaliacoesRoute: typeof PortalAlunoAvaliacoesRoute
  PortalAlunoCarteirinhaRoute: typeof PortalAlunoCarteirinhaRoute
  PortalAlunoConfiguracoesRoute: typeof PortalAlunoConfiguracoesRoute
  PortalAlunoContratoRoute: typeof PortalAlunoContratoRoute
  PortalAlunoDashboardRoute: typeof PortalAlunoDashboardRoute
  PortalAlunoFinanceiroRoute: typeof PortalAlunoFinanceiroRoute
  PortalAlunoMeuPlanoRoute: typeof PortalAlunoMeuPlanoRoute
  PortalAlunoNotificacoesRoute: typeof PortalAlunoNotificacoesRoute
  PortalAlunoPerfilRoute: typeof PortalAlunoPerfilRoute
  PortalAlunoPresencasRoute: typeof PortalAlunoPresencasRoute
  PortalAlunoTreinosRoute: typeof PortalAlunoTreinosRoute
  PortalResponsavelAgendaRoute: typeof PortalResponsavelAgendaRoute
  PortalResponsavelConfiguracoesRoute: typeof PortalResponsavelConfiguracoesRoute
  PortalResponsavelContratoRoute: typeof PortalResponsavelContratoRoute
  PortalResponsavelDashboardRoute: typeof PortalResponsavelDashboardRoute
  PortalResponsavelFinanceiroRoute: typeof PortalResponsavelFinanceiroRoute
  PortalResponsavelMeusFilhosRoute: typeof PortalResponsavelMeusFilhosRoute
  PortalResponsavelNotificacoesRoute: typeof PortalResponsavelNotificacoesRoute
  PortalResponsavelPerfilRoute: typeof PortalResponsavelPerfilRoute
  PortalResponsavelPresencasRoute: typeof PortalResponsavelPresencasRoute
  ProfessorPresencasRoute: typeof ProfessorPresencasRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  PortalAlunoIndexRoute: typeof PortalAlunoIndexRoute
  PortalResponsavelIndexRoute: typeof PortalResponsavelIndexRoute
  ProfessorIndexRoute: typeof ProfessorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores': {
      id: '/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof ProfessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presencas': {
      id: '/presencas'
      path: '/presencas'
      fullPath: '/presencas'
      preLoaderRoute: typeof PresencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenca': {
      id: '/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof PresencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-plano': {
      id: '/meu-plano'
      path: '/meu-plano'
      fullPath: '/meu-plano'
      preLoaderRoute: typeof MeuPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos': {
      id: '/campeonatos'
      path: '/campeonatos'
      fullPath: '/campeonatos'
      preLoaderRoute: typeof CampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula-experimental': {
      id: '/aula-experimental'
      path: '/aula-experimental'
      fullPath: '/aula-experimental'
      preLoaderRoute: typeof AulaExperimentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/': {
      id: '/professor/'
      path: '/professor'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/': {
      id: '/portal-responsavel/'
      path: '/portal-responsavel'
      fullPath: '/portal-responsavel/'
      preLoaderRoute: typeof PortalResponsavelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/': {
      id: '/portal-aluno/'
      path: '/portal-aluno'
      fullPath: '/portal-aluno/'
      preLoaderRoute: typeof PortalAlunoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/presencas': {
      id: '/professor/presencas'
      path: '/professor/presencas'
      fullPath: '/professor/presencas'
      preLoaderRoute: typeof ProfessorPresencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/presencas': {
      id: '/portal-responsavel/presencas'
      path: '/portal-responsavel/presencas'
      fullPath: '/portal-responsavel/presencas'
      preLoaderRoute: typeof PortalResponsavelPresencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/perfil': {
      id: '/portal-responsavel/perfil'
      path: '/portal-responsavel/perfil'
      fullPath: '/portal-responsavel/perfil'
      preLoaderRoute: typeof PortalResponsavelPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/notificacoes': {
      id: '/portal-responsavel/notificacoes'
      path: '/portal-responsavel/notificacoes'
      fullPath: '/portal-responsavel/notificacoes'
      preLoaderRoute: typeof PortalResponsavelNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/meus-filhos': {
      id: '/portal-responsavel/meus-filhos'
      path: '/portal-responsavel/meus-filhos'
      fullPath: '/portal-responsavel/meus-filhos'
      preLoaderRoute: typeof PortalResponsavelMeusFilhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/financeiro': {
      id: '/portal-responsavel/financeiro'
      path: '/portal-responsavel/financeiro'
      fullPath: '/portal-responsavel/financeiro'
      preLoaderRoute: typeof PortalResponsavelFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/dashboard': {
      id: '/portal-responsavel/dashboard'
      path: '/portal-responsavel/dashboard'
      fullPath: '/portal-responsavel/dashboard'
      preLoaderRoute: typeof PortalResponsavelDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/contrato': {
      id: '/portal-responsavel/contrato'
      path: '/portal-responsavel/contrato'
      fullPath: '/portal-responsavel/contrato'
      preLoaderRoute: typeof PortalResponsavelContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/configuracoes': {
      id: '/portal-responsavel/configuracoes'
      path: '/portal-responsavel/configuracoes'
      fullPath: '/portal-responsavel/configuracoes'
      preLoaderRoute: typeof PortalResponsavelConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-responsavel/agenda': {
      id: '/portal-responsavel/agenda'
      path: '/portal-responsavel/agenda'
      fullPath: '/portal-responsavel/agenda'
      preLoaderRoute: typeof PortalResponsavelAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/treinos': {
      id: '/portal-aluno/treinos'
      path: '/portal-aluno/treinos'
      fullPath: '/portal-aluno/treinos'
      preLoaderRoute: typeof PortalAlunoTreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/presencas': {
      id: '/portal-aluno/presencas'
      path: '/portal-aluno/presencas'
      fullPath: '/portal-aluno/presencas'
      preLoaderRoute: typeof PortalAlunoPresencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/perfil': {
      id: '/portal-aluno/perfil'
      path: '/portal-aluno/perfil'
      fullPath: '/portal-aluno/perfil'
      preLoaderRoute: typeof PortalAlunoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/notificacoes': {
      id: '/portal-aluno/notificacoes'
      path: '/portal-aluno/notificacoes'
      fullPath: '/portal-aluno/notificacoes'
      preLoaderRoute: typeof PortalAlunoNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/meu-plano': {
      id: '/portal-aluno/meu-plano'
      path: '/portal-aluno/meu-plano'
      fullPath: '/portal-aluno/meu-plano'
      preLoaderRoute: typeof PortalAlunoMeuPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/financeiro': {
      id: '/portal-aluno/financeiro'
      path: '/portal-aluno/financeiro'
      fullPath: '/portal-aluno/financeiro'
      preLoaderRoute: typeof PortalAlunoFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/dashboard': {
      id: '/portal-aluno/dashboard'
      path: '/portal-aluno/dashboard'
      fullPath: '/portal-aluno/dashboard'
      preLoaderRoute: typeof PortalAlunoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/contrato': {
      id: '/portal-aluno/contrato'
      path: '/portal-aluno/contrato'
      fullPath: '/portal-aluno/contrato'
      preLoaderRoute: typeof PortalAlunoContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/configuracoes': {
      id: '/portal-aluno/configuracoes'
      path: '/portal-aluno/configuracoes'
      fullPath: '/portal-aluno/configuracoes'
      preLoaderRoute: typeof PortalAlunoConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/carteirinha': {
      id: '/portal-aluno/carteirinha'
      path: '/portal-aluno/carteirinha'
      fullPath: '/portal-aluno/carteirinha'
      preLoaderRoute: typeof PortalAlunoCarteirinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/avaliacoes': {
      id: '/portal-aluno/avaliacoes'
      path: '/portal-aluno/avaliacoes'
      fullPath: '/portal-aluno/avaliacoes'
      preLoaderRoute: typeof PortalAlunoAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-aluno/agenda': {
      id: '/portal-aluno/agenda'
      path: '/portal-aluno/agenda'
      fullPath: '/portal-aluno/agenda'
      preLoaderRoute: typeof PortalAlunoAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$championshipId': {
      id: '/campeonatos/$championshipId'
      path: '/$championshipId'
      fullPath: '/campeonatos/$championshipId'
      preLoaderRoute: typeof CampeonatosChampionshipIdRouteImport
      parentRoute: typeof CampeonatosRoute
    }
    '/admin/quadras': {
      id: '/admin/quadras'
      path: '/admin/quadras'
      fullPath: '/admin/quadras'
      preLoaderRoute: typeof AdminQuadrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command-center-students-preview': {
      id: '/admin/command-center-students-preview'
      path: '/admin/command-center-students-preview'
      fullPath: '/admin/command-center-students-preview'
      preLoaderRoute: typeof AdminCommandCenterStudentsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command-center-preview': {
      id: '/admin/command-center-preview'
      path: '/admin/command-center-preview'
      fullPath: '/admin/command-center-preview'
      preLoaderRoute: typeof AdminCommandCenterPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command-center-financial-preview': {
      id: '/admin/command-center-financial-preview'
      path: '/admin/command-center-financial-preview'
      fullPath: '/admin/command-center-financial-preview'
      preLoaderRoute: typeof AdminCommandCenterFinancialPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command-center-enrollment-preview': {
      id: '/admin/command-center-enrollment-preview'
      path: '/admin/command-center-enrollment-preview'
      fullPath: '/admin/command-center-enrollment-preview'
      preLoaderRoute: typeof AdminCommandCenterEnrollmentPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campeonatos': {
      id: '/admin/campeonatos'
      path: '/admin/campeonatos'
      fullPath: '/admin/campeonatos'
      preLoaderRoute: typeof AdminCampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bi': {
      id: '/admin/bi'
      path: '/admin/bi'
      fullPath: '/admin/bi'
      preLoaderRoute: typeof AdminBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/admin/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/aluno/$id': {
      id: '/dashboard/aluno/$id'
      path: '/aluno/$id'
      fullPath: '/dashboard/aluno/$id'
      preLoaderRoute: typeof DashboardAlunoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/campeonatos/inscricoes': {
      id: '/admin/campeonatos/inscricoes'
      path: '/inscricoes'
      fullPath: '/admin/campeonatos/inscricoes'
      preLoaderRoute: typeof AdminCampeonatosInscricoesRouteImport
      parentRoute: typeof AdminCampeonatosRoute
    }
    '/admin/bi/turmas': {
      id: '/admin/bi/turmas'
      path: '/turmas'
      fullPath: '/admin/bi/turmas'
      preLoaderRoute: typeof AdminBiTurmasRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/bi/relatorios': {
      id: '/admin/bi/relatorios'
      path: '/relatorios'
      fullPath: '/admin/bi/relatorios'
      preLoaderRoute: typeof AdminBiRelatoriosRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/bi/quadras': {
      id: '/admin/bi/quadras'
      path: '/quadras'
      fullPath: '/admin/bi/quadras'
      preLoaderRoute: typeof AdminBiQuadrasRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/bi/insights': {
      id: '/admin/bi/insights'
      path: '/insights'
      fullPath: '/admin/bi/insights'
      preLoaderRoute: typeof AdminBiInsightsRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/bi/inadimplencia': {
      id: '/admin/bi/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/admin/bi/inadimplencia'
      preLoaderRoute: typeof AdminBiInadimplenciaRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/bi/financeiro': {
      id: '/admin/bi/financeiro'
      path: '/financeiro'
      fullPath: '/admin/bi/financeiro'
      preLoaderRoute: typeof AdminBiFinanceiroRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/bi/campeonatos': {
      id: '/admin/bi/campeonatos'
      path: '/campeonatos'
      fullPath: '/admin/bi/campeonatos'
      preLoaderRoute: typeof AdminBiCampeonatosRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/bi/alunos': {
      id: '/admin/bi/alunos'
      path: '/alunos'
      fullPath: '/admin/bi/alunos'
      preLoaderRoute: typeof AdminBiAlunosRouteImport
      parentRoute: typeof AdminBiRoute
    }
    '/admin/financeiro/automacoes/historico': {
      id: '/admin/financeiro/automacoes/historico'
      path: '/automacoes/historico'
      fullPath: '/admin/financeiro/automacoes/historico'
      preLoaderRoute: typeof AdminFinanceiroAutomacoesHistoricoRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/campeonatos/$championshipId/rodadas': {
      id: '/admin/campeonatos/$championshipId/rodadas'
      path: '/$championshipId/rodadas'
      fullPath: '/admin/campeonatos/$championshipId/rodadas'
      preLoaderRoute: typeof AdminCampeonatosChampionshipIdRodadasRouteImport
      parentRoute: typeof AdminCampeonatosRoute
    }
    '/admin/campeonatos/$championshipId/mata-mata': {
      id: '/admin/campeonatos/$championshipId/mata-mata'
      path: '/$championshipId/mata-mata'
      fullPath: '/admin/campeonatos/$championshipId/mata-mata'
      preLoaderRoute: typeof AdminCampeonatosChampionshipIdMataMataRouteImport
      parentRoute: typeof AdminCampeonatosRoute
    }
    '/admin/campeonatos/$championshipId/grupos': {
      id: '/admin/campeonatos/$championshipId/grupos'
      path: '/$championshipId/grupos'
      fullPath: '/admin/campeonatos/$championshipId/grupos'
      preLoaderRoute: typeof AdminCampeonatosChampionshipIdGruposRouteImport
      parentRoute: typeof AdminCampeonatosRoute
    }
    '/admin/campeonatos/$championshipId/estatisticas': {
      id: '/admin/campeonatos/$championshipId/estatisticas'
      path: '/$championshipId/estatisticas'
      fullPath: '/admin/campeonatos/$championshipId/estatisticas'
      preLoaderRoute: typeof AdminCampeonatosChampionshipIdEstatisticasRouteImport
      parentRoute: typeof AdminCampeonatosRoute
    }
    '/admin/campeonatos/$championshipId/classificacao': {
      id: '/admin/campeonatos/$championshipId/classificacao'
      path: '/$championshipId/classificacao'
      fullPath: '/admin/campeonatos/$championshipId/classificacao'
      preLoaderRoute: typeof AdminCampeonatosChampionshipIdClassificacaoRouteImport
      parentRoute: typeof AdminCampeonatosRoute
    }
    '/admin/campeonatos/inscricoes/$registrationId/atletas': {
      id: '/admin/campeonatos/inscricoes/$registrationId/atletas'
      path: '/$registrationId/atletas'
      fullPath: '/admin/campeonatos/inscricoes/$registrationId/atletas'
      preLoaderRoute: typeof AdminCampeonatosInscricoesRegistrationIdAtletasRouteImport
      parentRoute: typeof AdminCampeonatosInscricoesRoute
    }
    '/admin/campeonatos/$championshipId/jogos/$matchId/sumula': {
      id: '/admin/campeonatos/$championshipId/jogos/$matchId/sumula'
      path: '/$championshipId/jogos/$matchId/sumula'
      fullPath: '/admin/campeonatos/$championshipId/jogos/$matchId/sumula'
      preLoaderRoute: typeof AdminCampeonatosChampionshipIdJogosMatchIdSumulaRouteImport
      parentRoute: typeof AdminCampeonatosRoute
    }
  }
}

interface CampeonatosRouteChildren {
  CampeonatosChampionshipIdRoute: typeof CampeonatosChampionshipIdRoute
}

const CampeonatosRouteChildren: CampeonatosRouteChildren = {
  CampeonatosChampionshipIdRoute: CampeonatosChampionshipIdRoute,
}

const CampeonatosRouteWithChildren = CampeonatosRoute._addFileChildren(
  CampeonatosRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAlunoIdRoute: typeof DashboardAlunoIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlunoIdRoute: DashboardAlunoIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminBiRouteChildren {
  AdminBiAlunosRoute: typeof AdminBiAlunosRoute
  AdminBiCampeonatosRoute: typeof AdminBiCampeonatosRoute
  AdminBiFinanceiroRoute: typeof AdminBiFinanceiroRoute
  AdminBiInadimplenciaRoute: typeof AdminBiInadimplenciaRoute
  AdminBiInsightsRoute: typeof AdminBiInsightsRoute
  AdminBiQuadrasRoute: typeof AdminBiQuadrasRoute
  AdminBiRelatoriosRoute: typeof AdminBiRelatoriosRoute
  AdminBiTurmasRoute: typeof AdminBiTurmasRoute
}

const AdminBiRouteChildren: AdminBiRouteChildren = {
  AdminBiAlunosRoute: AdminBiAlunosRoute,
  AdminBiCampeonatosRoute: AdminBiCampeonatosRoute,
  AdminBiFinanceiroRoute: AdminBiFinanceiroRoute,
  AdminBiInadimplenciaRoute: AdminBiInadimplenciaRoute,
  AdminBiInsightsRoute: AdminBiInsightsRoute,
  AdminBiQuadrasRoute: AdminBiQuadrasRoute,
  AdminBiRelatoriosRoute: AdminBiRelatoriosRoute,
  AdminBiTurmasRoute: AdminBiTurmasRoute,
}

const AdminBiRouteWithChildren =
  AdminBiRoute._addFileChildren(AdminBiRouteChildren)

interface AdminCampeonatosInscricoesRouteChildren {
  AdminCampeonatosInscricoesRegistrationIdAtletasRoute: typeof AdminCampeonatosInscricoesRegistrationIdAtletasRoute
}

const AdminCampeonatosInscricoesRouteChildren: AdminCampeonatosInscricoesRouteChildren =
  {
    AdminCampeonatosInscricoesRegistrationIdAtletasRoute:
      AdminCampeonatosInscricoesRegistrationIdAtletasRoute,
  }

const AdminCampeonatosInscricoesRouteWithChildren =
  AdminCampeonatosInscricoesRoute._addFileChildren(
    AdminCampeonatosInscricoesRouteChildren,
  )

interface AdminCampeonatosRouteChildren {
  AdminCampeonatosInscricoesRoute: typeof AdminCampeonatosInscricoesRouteWithChildren
  AdminCampeonatosChampionshipIdClassificacaoRoute: typeof AdminCampeonatosChampionshipIdClassificacaoRoute
  AdminCampeonatosChampionshipIdEstatisticasRoute: typeof AdminCampeonatosChampionshipIdEstatisticasRoute
  AdminCampeonatosChampionshipIdGruposRoute: typeof AdminCampeonatosChampionshipIdGruposRoute
  AdminCampeonatosChampionshipIdMataMataRoute: typeof AdminCampeonatosChampionshipIdMataMataRoute
  AdminCampeonatosChampionshipIdRodadasRoute: typeof AdminCampeonatosChampionshipIdRodadasRoute
  AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute: typeof AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute
}

const AdminCampeonatosRouteChildren: AdminCampeonatosRouteChildren = {
  AdminCampeonatosInscricoesRoute: AdminCampeonatosInscricoesRouteWithChildren,
  AdminCampeonatosChampionshipIdClassificacaoRoute:
    AdminCampeonatosChampionshipIdClassificacaoRoute,
  AdminCampeonatosChampionshipIdEstatisticasRoute:
    AdminCampeonatosChampionshipIdEstatisticasRoute,
  AdminCampeonatosChampionshipIdGruposRoute:
    AdminCampeonatosChampionshipIdGruposRoute,
  AdminCampeonatosChampionshipIdMataMataRoute:
    AdminCampeonatosChampionshipIdMataMataRoute,
  AdminCampeonatosChampionshipIdRodadasRoute:
    AdminCampeonatosChampionshipIdRodadasRoute,
  AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute:
    AdminCampeonatosChampionshipIdJogosMatchIdSumulaRoute,
}

const AdminCampeonatosRouteWithChildren =
  AdminCampeonatosRoute._addFileChildren(AdminCampeonatosRouteChildren)

interface AdminFinanceiroRouteChildren {
  AdminFinanceiroAutomacoesHistoricoRoute: typeof AdminFinanceiroAutomacoesHistoricoRoute
}

const AdminFinanceiroRouteChildren: AdminFinanceiroRouteChildren = {
  AdminFinanceiroAutomacoesHistoricoRoute:
    AdminFinanceiroAutomacoesHistoricoRoute,
}

const AdminFinanceiroRouteWithChildren = AdminFinanceiroRoute._addFileChildren(
  AdminFinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlunosRoute: AlunosRoute,
  AulaExperimentalRoute: AulaExperimentalRoute,
  CampeonatosRoute: CampeonatosRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MatriculaRoute: MatriculaRoute,
  MeuPlanoRoute: MeuPlanoRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PresencaRoute: PresencaRoute,
  PresencasRoute: PresencasRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  ProfessoresRoute: ProfessoresRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  TurmasRoute: TurmasRoute,
  AdminAgendaRoute: AdminAgendaRoute,
  AdminBiRoute: AdminBiRouteWithChildren,
  AdminCampeonatosRoute: AdminCampeonatosRouteWithChildren,
  AdminCommandCenterEnrollmentPreviewRoute:
    AdminCommandCenterEnrollmentPreviewRoute,
  AdminCommandCenterFinancialPreviewRoute:
    AdminCommandCenterFinancialPreviewRoute,
  AdminCommandCenterPreviewRoute: AdminCommandCenterPreviewRoute,
  AdminCommandCenterStudentsPreviewRoute:
    AdminCommandCenterStudentsPreviewRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminFinanceiroRoute: AdminFinanceiroRouteWithChildren,
  AdminQuadrasRoute: AdminQuadrasRoute,
  PortalAlunoAgendaRoute: PortalAlunoAgendaRoute,
  PortalAlunoAvaliacoesRoute: PortalAlunoAvaliacoesRoute,
  PortalAlunoCarteirinhaRoute: PortalAlunoCarteirinhaRoute,
  PortalAlunoConfiguracoesRoute: PortalAlunoConfiguracoesRoute,
  PortalAlunoContratoRoute: PortalAlunoContratoRoute,
  PortalAlunoDashboardRoute: PortalAlunoDashboardRoute,
  PortalAlunoFinanceiroRoute: PortalAlunoFinanceiroRoute,
  PortalAlunoMeuPlanoRoute: PortalAlunoMeuPlanoRoute,
  PortalAlunoNotificacoesRoute: PortalAlunoNotificacoesRoute,
  PortalAlunoPerfilRoute: PortalAlunoPerfilRoute,
  PortalAlunoPresencasRoute: PortalAlunoPresencasRoute,
  PortalAlunoTreinosRoute: PortalAlunoTreinosRoute,
  PortalResponsavelAgendaRoute: PortalResponsavelAgendaRoute,
  PortalResponsavelConfiguracoesRoute: PortalResponsavelConfiguracoesRoute,
  PortalResponsavelContratoRoute: PortalResponsavelContratoRoute,
  PortalResponsavelDashboardRoute: PortalResponsavelDashboardRoute,
  PortalResponsavelFinanceiroRoute: PortalResponsavelFinanceiroRoute,
  PortalResponsavelMeusFilhosRoute: PortalResponsavelMeusFilhosRoute,
  PortalResponsavelNotificacoesRoute: PortalResponsavelNotificacoesRoute,
  PortalResponsavelPerfilRoute: PortalResponsavelPerfilRoute,
  PortalResponsavelPresencasRoute: PortalResponsavelPresencasRoute,
  ProfessorPresencasRoute: ProfessorPresencasRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  PortalAlunoIndexRoute: PortalAlunoIndexRoute,
  PortalResponsavelIndexRoute: PortalResponsavelIndexRoute,
  ProfessorIndexRoute: ProfessorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
